# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
