# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_auto_20161011_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='notes',
        ),
        migrations.AddField(
            model_name='hotel',
            name='chambres',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='note',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=2),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(),
        ),
    ]
